export const sampleTexts = [
  `The concept of time has fascinated philosophers and scientists for millennia. Is it a fundamental property of the universe, or merely a construct of human perception? We measure its passage with incredible precision using atomic clocks, yet we often speak of it flying or dragging based on our subjective experience. This dichotomy between objective measurement and subjective feeling lies at the heart of our relationship with time. Modern physics adds further layers of mystery, suggesting that time may be relative, its flow affected by gravity and velocity. The arrow of time, always moving forward, is tied to the concept of entropy and the irreversible nature of the universe's expansion. Despite our advanced understanding, time remains an elusive and deeply profound concept, reminding us that some of the most fundamental aspects of existence are also the most difficult to fully comprehend and define. Our daily lives are governed by its strict schedule, yet our minds can travel through past and future in an instant, defying the very linearity we are bound by.`,

  `Sustainable agriculture represents a critical shift in how we produce food for a growing global population. It moves beyond traditional methods that often deplete soil nutrients and rely heavily on chemical pesticides, towards a more holistic approach. This philosophy emphasizes long-term health of the ecosystem, focusing on soil vitality, water conservation, and biodiversity. Techniques such as crop rotation, which prevents nutrient depletion, and polyculture, which involves growing multiple crop species together, mimic natural ecosystems and reduce the need for external inputs. Integrated pest management uses natural predators and organic solutions to control pests, protecting both the environment and consumer health. The benefits extend far beyond the farm, contributing to cleaner water, healthier soils that sequester carbon, and more resilient food systems in the face of climate change. It is a commitment to meeting our present needs without compromising the ability of future generations to meet their own, recognizing that human health is inextricably linked to the health of the planet.`,

  `The rise of digital communication has fundamentally reshaped human interaction, creating a world more connected than ever before. Through instant messaging, social media, and video calls, geographical barriers have become almost meaningless. We can maintain relationships across continents and share ideas with a global audience at the click of a button. This hyper-connectivity has fueled social movements, democratized information, and created new forms of community and collaboration. However, this new landscape is not without its challenges. The constant stream of notifications can lead to information overload and anxiety. The lack of non-verbal cues in text-based communication can sometimes foster misunderstanding and conflict. Furthermore, the curated nature of online personas can create unrealistic expectations and damage self-esteem. .`,

  `Urban planning in the 21st century faces the immense challenge of creating cities that are not only efficient but also livable and sustainable. The old model of car-centric design, with its sprawling suburbs and congested highways, is increasingly being reconsidered. In its place, a new vision emphasizes mixed-use development, robust public transportation, and green spaces. The goal is to create walkable, bikeable communities where residents can live, work, and play without lengthy commutes. This approach reduces a city's carbon footprint, mitigates air and noise pollution, and fosters a stronger sense of community. `
];

export function chunkWords(words: string[], wordsPerLine: number) {
  const chunks = [];
  for (let i = 0; i < words.length; i += wordsPerLine) {
    chunks.push(words.slice(i, i + wordsPerLine));
  }
  return chunks;
}
